// Generated by scripts/build-mcp-widgets.mjs. Do not edit manually.
export const WIDGET_ASSETS = {
  workspace: {
    script: "workspace-JMR5KLLP.js",
    stylesheet: "workspace-XTSWDRWC.css",
  },
  "post-editor": {
    script: "post-editor-2M2GR4VC.js",
    stylesheet: "post-editor-5D32XD7Q.css",
  },
  schedule: {
    script: "schedule-TCDLEUAI.js",
    stylesheet: "schedule-2DSVH726.css",
  },
  "post-preview": {
    script: "post-preview-GDHLAQBG.js",
    stylesheet: "post-preview-D6X276YG.css",
  },
} as const;

export type WidgetName = keyof typeof WIDGET_ASSETS;
