// Generated by scripts/build-mcp-widgets.mjs. Do not edit manually.
export const WIDGET_ASSETS = {
  workspace: {
    script: "workspace-34JT7XQ6.js",
    stylesheet: "workspace-UYD72CC2.css",
  },
  "post-editor": {
    script: "post-editor-O2Y56EFR.js",
    stylesheet: "post-editor-P2HEM56K.css",
  },
  schedule: {
    script: "schedule-73CJUGN4.js",
    stylesheet: "schedule-RJJ52SVY.css",
  },
  "post-preview": {
    script: "post-preview-MBE3TNNW.js",
    stylesheet: "post-preview-DVPTLTLP.css",
  },
} as const;

export type WidgetName = keyof typeof WIDGET_ASSETS;
