// Generated by scripts/build-mcp-widgets.mjs. Do not edit manually.
export const WIDGET_ASSETS = {
  workspace: {
    script: "workspace-XJHTEND6.js",
    stylesheet: "workspace-DVXCKYXY.css",
  },
  "post-editor": {
    script: "post-editor-3VO7ZIVM.js",
    stylesheet: "post-editor-S3HIITF5.css",
  },
  schedule: {
    script: "schedule-73CJUGN4.js",
    stylesheet: "schedule-SDAPV46T.css",
  },
  "post-preview": {
    script: "post-preview-MBE3TNNW.js",
    stylesheet: "post-preview-DVPTLTLP.css",
  },
} as const;

export type WidgetName = keyof typeof WIDGET_ASSETS;
