import * as z from "zod/v4";

import { basicErrorResponses, defineRoute, jsonResponse } from "@/lib/openapi/helpers";
import { JsonValueSchema } from "@/lib/openapi/schemas";

const AuthResponseSchema = z.record(z.string(), JsonValueSchema).meta({
  id: "BetterAuthResponse",
  description: "Response generated by Better Auth for the requested auth sub-route.",
});

const requestParams = {
  path: z.object({
    path: z.string().meta({
      description: "Better Auth route segment.",
      example: "session",
    }),
  }),
};

export default defineRoute({
  path: "/api/auth/{path}",
  methods: {
    get: {
      operationId: "getAuthRoute",
      tags: ["Auth"],
      summary: "Handle Better Auth GET routes",
      description: "Catch-all Better Auth endpoint for session, callback, and provider routes.",
      requestParams,
      responses: {
        "200": jsonResponse("Better Auth response.", AuthResponseSchema),
        ...basicErrorResponses,
      },
    },
    post: {
      operationId: "postAuthRoute",
      tags: ["Auth"],
      summary: "Handle Better Auth POST routes",
      description: "Catch-all Better Auth endpoint for sign-in, sign-out, and callback mutations.",
      requestParams,
      responses: {
        "200": jsonResponse("Better Auth response.", AuthResponseSchema),
        ...basicErrorResponses,
      },
    },
  },
});
