import type { Scenario, Platform, MediaKey, Options } from "./types.js";

// Shared by live MCP validation and isolated SDK/CLI process tests. Each case
// names the actual violation, so authentication/network errors cannot pass it.
function invalid(
  platform: Platform,
  name: string,
  media: MediaKey[],
  code: string,
  expectedError: string,
  options: Options = {},
  message = "Validation regression",
  detail: Partial<NonNullable<Scenario["expectedIssue"]>> = {},
): Scenario {
  return {
    id: `${platform}.validation-${name}`,
    platform,
    media,
    options,
    message,
    expectedError,
    expectedIssue: { code, ...detail },
    tags: ["full", "negative", "validation"],
    // Validation-only live calls; never risk posting invalid test content.
    interfaces: ["mcp"],
  };
}
export const validationCases: readonly Scenario[] = [
  invalid(
    "instagram",
    "portrait-ratio",
    ["narrowImage"],
    "media_aspect_ratio_unsupported",
    "aspect_ratio",
    {},
    undefined,
    { field: "media[0]", actual: 0.5, limit: 0.8 },
  ),
  invalid(
    "instagram",
    "carousel-child-ratio",
    ["image", "narrowImage"],
    "media_aspect_ratio_unsupported",
    "aspect_ratio",
    {},
    undefined,
    { field: "media[1]" },
  ),
  invalid(
    "instagram",
    "short-reel",
    ["shortVideo"],
    "media_duration_seconds_unsupported",
    "duration_seconds",
    {},
    undefined,
    { field: "media[0]", actual: 1, limit: 3 },
  ),
  invalid(
    "instagram",
    "slow-reel",
    ["slowVideo"],
    "media_frames_per_second_unsupported",
    "frames_per_second",
    {},
    undefined,
    { actual: 15, limit: 23 },
  ),
  invalid("tiktok", "large-photo", ["largeImage"], "photo_dimensions_too_large", "Resize|dimensions"),
  invalid(
    "tiktok",
    "slow-video",
    ["slowVideo"],
    "media_frames_per_second_unsupported",
    "frames_per_second",
    { privacyLevel: "SELF_ONLY" },
    undefined,
    { actual: 15, limit: 23 },
  ),
  invalid("tiktok", "cover-index", ["image"], "photo_cover_invalid", "cover|index", {
    photoCoverIndex: 1,
    privacyLevel: "SELF_ONLY",
  }),
  invalid("bluesky", "unicode-bytes", [], "text_bytes_exceeded", "3000|3,000|bytes", {}, "👨‍👩‍👧‍👦".repeat(121), {
    actual: 3025,
    limit: 3000,
  }),
  invalid("bluesky", "disguised-container", ["disguisedVideo"], "video_format_unsupported", "MP4"),
  invalid(
    "telegram",
    "image-dimensions",
    ["largeImage"],
    "media_width_plus_height_unsupported",
    "width_plus_height",
    {},
    undefined,
    { actual: 12040, limit: 10000 },
  ),
  invalid(
    "telegram",
    "html",
    [],
    "telegram_entities_invalid",
    "HTML|markup|tag",
    { parseMode: "HTML" },
    "<b><i>crossed</b></i>",
  ),
  invalid("telegram", "markdown", [], "telegram_entities_invalid", "Markdown", { parseMode: "Markdown" }, "*unclosed"),
  invalid(
    "telegram",
    "markdown-v2",
    [],
    "telegram_entities_invalid",
    "MarkdownV2",
    { parseMode: "MarkdownV2" },
    "unescaped.",
  ),
  invalid(
    "telegram",
    "decoded-caption",
    ["image"],
    "telegram_text_too_long",
    "1024",
    { parseMode: "HTML" },
    `<b>${"&amp;".repeat(1025)}</b>`,
    { actual: 1025, limit: 1024 },
  ),
  invalid(
    "youtube",
    "description-bytes",
    ["video"],
    "description_too_long",
    "5000|5,000",
    { title: "Short", description: "é".repeat(2501) },
    undefined,
    { field: "description", actual: 5002, limit: 5000 },
  ),
  invalid("youtube", "derived-title", ["video"], "title_too_long", "100|title", {}, "T".repeat(101), {
    actual: 101,
    limit: 100,
  }),
  invalid("youtube", "title-characters", ["video"], "title_invalid_characters", "title|characters", { title: "<bad>" }),
  invalid("youtube", "aggregate-tags", ["video"], "tags_too_long", "tags", { tags: ["a ".repeat(250)] }, undefined, {
    field: "tags",
    actual: 502,
    limit: 500,
  }),
  invalid("youtube", "native-schedule", ["video"], "publish_time_past", "future", {
    publishAt: "2000-01-01T00:00:00Z",
  }),
  invalid("x", "video-codec", ["disguisedVideo"], "video_codec_unsupported", "codec|unsupported|h264"),
  invalid("linkedin", "image-pixels", ["largeImage"], "media_pixel_count_unsupported", "pixel_count", {}, undefined, {
    actual: 36240400,
    limit: 36152319,
  }),
  invalid(
    "threads",
    "video-frame-rate",
    ["slowVideo"],
    "media_frames_per_second_unsupported",
    "frames_per_second",
    {},
    undefined,
    { actual: 15, limit: 23 },
  ),
  invalid("facebook", "native-schedule", [], "publish_time_past", "future", { publishAt: "2000-01-01T00:00:00Z" }),
  invalid(
    "pinterest",
    "description-override",
    ["image"],
    "description_too_long",
    "800",
    { description: "D".repeat(801) },
    undefined,
    { actual: 801, limit: 800 },
  ),
  invalid("pinterest", "alt-text", ["image"], "altText_too_long", "500", { altText: "A".repeat(501) }, undefined, {
    actual: 501,
    limit: 500,
  }),
  invalid("pinterest", "board", ["image"], "board_invalid", "numeric|board", { boardId: "not-numeric" }),
  invalid(
    "pinterest",
    "short-video",
    ["shortVideo"],
    "media_duration_seconds_unsupported",
    "duration_seconds",
    {},
    undefined,
    { actual: 1, limit: 4 },
  ),
  invalid("forem", "title", [], "title_too_long", "128", { title: "T".repeat(129) }, undefined, {
    actual: 129,
    limit: 128,
  }),
  invalid("forem", "tag-syntax", [], "tag_invalid", "tags", { tags: ["bad-tag"] }),
  invalid("forem", "frontmatter", [], "frontmatter_unsupported", "front matter", {}, "---\ntitle: hidden\n---\nBody"),
];
