name: Run Checks and Tests

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run checks
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: yarn check

      - name: Run SDK tests with coverage
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: yarn test:coverage

      - name: Run CLI tests
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: yarn workspace @simple-post/cli test

      - name: Run Scheduler tests
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: yarn workspace @simple-post/scheduler test

      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        if: success()
        with:
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
